apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit737-task6c-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sit737-task6c
  template:
    metadata:
      labels:
        app: sit737-task6c
    spec:
      containers:
      - name: sit737-task6p-container
        image: sit737-task6c-app:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 3000