apiVersion: v1
kind: Service
metadata:
  name: sit737-task6p-service
spec:
  type: NodePort
  selector:
      app: sit737-task6p
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30010